### ISSUE TITLE
Ask for advice, how do you drive the graphics card can you elaborate?

### ISSUE THREAD

**Issue by frozenzero123** [KhoraLee/Lenovo-Ideapad-Slim3-14iil05-Hackintosh#1]
My device is yoga S740. After using your efi, it is now switched to 0C, but the graphics card still cannot be driven. I want to ask for your help！
Equipment: yoga s740 (China version)
Graphics: Iris Plus940
CPU: i7 1065G7
SSD: WD Blue SN550 NVMe SSD 1T (after pm981a replacement)
Sound card: ALC285 and inter sst mic
Memory: ddr4x 3733 16G (micron)
BIOS: BYCN35WW
CFG lock: Disabled (changed)
DVMT: 64M (changed)

**Comment by KhoraLee** [comment]
I saw your comment on X86.co.kr . I did nothing special... I just added' AAPL,ig-platform-id : 0000528A' property and it worked for me (G4 Graphics). 
I think your graphic problem might be related to WEG...

**Comment by frozenzero123** [comment]
> 我看到了您对X86.co.kr的评论。我没有做任何特别的事情...我刚刚添加了“ AAPL，ig-platform-id：0000528A”属性，它对我有用（G4图形）。
> 我认为您的图形问题可能与WEG有关...
thank you
